### ISSUE TITLE
credo-language-server fails to start

### ISSUE THREAD

**Issue by barkerja** [elixir-tools/credo-language-server#67]
I just installed v0.2.2. Watching the output for Credo, after my application fully compiles, I see the following error:

```
[Error - 2:34:25 PM] Stopping server failed
Error: Stopping the server timed out
    at /Users/john/.vscode-insiders/extensions/elixir-tools.elixir-tools-0.2.2/dist/extension.js:2:150423
[Error - 2:34:25 PM] Stopping server failed
Error: Stopping the server timed out
    at /Users/john/.vscode-insiders/extensions/elixir-tools.elixir-tools-0.2.2/dist/extension.js:2:150423
[Error - 2:34:25 PM] Stopping server failed
Error: Stopping the server timed out
    at /Users/john/.vscode-insiders/extensions/elixir-tools.elixir-tools-0.2.2/dist/extension.js:2:150423
[Error - 2:34:25 PM] Stopping server failed
Error: Stopping the server timed out
    at /Users/john/.vscode-insiders/extensions/elixir-tools.elixir-tools-0.2.2/dist/extension.js:2:150423
[Error - 2:34:25 PM] Client Credo: connection to server is erroring. Shutting down server.
[Error - 2:34:25 PM] Client Credo: connection to server is erroring. Shutting down server.
...
```

The _connection to server is erroring._ error continues to repeat indefinitely.

Environment: `Elixir 1.14.2 (compiled with Erlang/OTP 24)`

If there is more info I can provide, please let me know how to do so! 🙏🏻

**Comment by iautom8things** [comment]
Hmm ... Maybe I wasn't because now it's working. and I do see the `credo-language-server 0.2.0` message. 

Is the language server doing something different than what credo does, out-of-the-box?  It doesn't make sense to me that the `_build` and `deps` folders need to be ignored since they weren't included via the `included:` attribute.  The elixir script I included shows what I'm talking about.  Credo doesn't attempt to source files from those folders if they aren't included in the `included:` attribute.

**Comment by mhanberg** [comment]
That was just a hypothesis. 

The fix that I found last night was a timeout. Credo took longer than the configured timeout so I set it to infinity. Unrelated to the config thing.

**Comment by iautom8things** [comment]
Gotchya! Okay.

So you'd expect this to work with 0.2.0 _without_ the changes to exclude `_build` and `deps`?

I am still getting a timeout error if I don't include that change.
